### ISSUE TITLE
Investigate wordpress

### ISSUE THREAD

**Issue by Karyum** [project-Saliba/online-courses-af#1]
check how we get a template through wordpress

**Comment by Karyum** [comment]
@Janooos I need a user for wordpress so i can access the templates, i'm only allowed to access them if im paying them monthly, so if you can send me your wordpress details on whatsapp or something? thanks

**Comment by Janooos** [comment]
Sending you, not sure it will work, because my hosting is expired

**Comment by Karyum** [comment]
@Janooos plez?
